# Generated by Django 2.1.7 on 2019-03-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='emp/')),
            ],
        ),
    ]
