# Generated by Django 2.1.7 on 2019-03-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app61', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='image',
        ),
    ]
